### ISSUE TITLE
Chisel 2.9.3.9 crash

### ISSUE THREAD

**Issue by WeaselOnaStick** [twothe/DaVincing#10] opened 2015-12-23 15:14 UTC
http://paste.ee/p/QQHA3

**Comment by twothe** [comment] 2015-12-23 15:42
`two.davincing.sculpture.SculptureBlock cannot be cast to team.chisel.ctmlib.ICTMBlock`

This is the essential part. This is duo to an incompatibility with Chisel (which has issues with several other mods).

For the moment I recommend to set chisel blocks on the blacklist in the Davincing config file. Afair there was such a list on the forum for copy & paste.

**Comment by twothe** [comment] 2015-12-23 15:43
Closed because duplicate of #9

**Closed as completed by twothe** 2015-12-23 15:43 UTC
